# Generated by Django 4.1.6 on 2023-02-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Scores',
            field=models.FloatField(null=True),
        ),
    ]
